# Generated by Django 4.1.7 on 2023-03-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_app', '0003_add_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_products',
            name='user',
        ),
    ]
