# Generated by Django 4.1.7 on 2023-03-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_app', '0008_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='user',
        ),
    ]
