# Generated by Django 4.1.7 on 2023-03-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent_app', '0010_event_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_register',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_app.artist_register'),
        ),
    ]
