# Generated by Django 4.1.7 on 2023-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_app', '0011_event_register_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='premium',
        ),
        migrations.AddField(
            model_name='add_events',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
