# Generated by Django 4.1.7 on 2023-04-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent_app', '0016_remove_payment_event_user_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_event',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_app.add_events'),
        ),
    ]
