# Generated by Django 4.1.7 on 2023-04-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent_app', '0017_payment_event_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_product',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_app.add_products'),
        ),
    ]
