# Generated by Django 4.1.7 on 2023-04-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent_app', '0019_feedback_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_product',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_app.artist_register'),
        ),
    ]
